name: Jets Workflow

on:
  push:
    branches:
      - main
jobs:
  environment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Test environment variable
        run: |
          echo $AWS_REGION
          echo $BUCKET_NAME
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build:
    runs-on: ubuntu-latest
    environment: dev
    needs: environment 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install dependencies
          |
          gem install bundler:2.2.21
          bundle install
      - name: Run Tests
        run: |
          bundle exec rspec
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  