name: Jets Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run script 
        run: echo Hello World!
        
  deploy-dev: 
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
      - name: Run script 
        run: echo  ${{ secrets.AWS_REGION }}
