name: Jets Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install dependencies
        run: |
          gem install bundler:2.2.21
          bundle install
  environment:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: Test environment variable
        run: echo $AWS_REGION
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
  test:
    runs-on: ubuntu-latest
    environment: dev
    needs: environment
    steps:
      - name: Run Tests
        run: |
          bundle exec rspec
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}